/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_patchinlinedemo_MainApplication */

#ifndef _Included_com_example_patchinlinedemo_MainApplication
#define _Included_com_example_patchinlinedemo_MainApplication
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_com_example_patchinlinedemo_MainApplication_clearDexCache
  (JNIEnv *, jobject, jlong, jint, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
